### ISSUE TITLE
compiled fortran issue with python3

### ISSUE THREAD

**Issue by dbowman234** [IvS-KULeuven/IvSPythonRepository#9]
After installing the IvS python repository (on 08/11/2018) and creating the condo environment following the ivs_repo_3.6.yml instructions on the wiki, I get an error when attempting to:
**import ivs.timeseries.freqanalyse as fa**
within the ivs_repo_3.6 environment

This is probably because there is a fundamental difference in the way that compiled fortran is called within python3.

- Dominic
- - - - - -
(ivs_repo_3.6) lich:Desktop dominic$ python
Python 3.6.2 |Anaconda, Inc.| (default, Oct  5 2017, 03:00:07) 
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import ivs.timeseries.freqanalyse as fa
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/dominic/python/ivs/timeseries/freqanalyse.py", line 155, in <module>
    from ivs.sigproc import fit
  File "/Users/dominic/python/ivs/sigproc/fit.py", line 437, in <module>
    from ivs.timeseries import pyKEP
ImportError: dlopen(/Users/dominic/python/ivs/timeseries/pyKEP.so, 2): Symbol not found: _PyCObject_Type
  Referenced from: /Users/dominic/python/ivs/timeseries/pyKEP.so
  Expected in: flat namespace
 in /Users/dominic/python/ivs/timeseries/pyKEP.so

**Comment by mike-ivs** [comment]
Do you still have this problem? I was unable to re-produce it on my Fedora machine. (the _PyCObject_Type issue is potentially a disjoint between Python versions, possibly caused by the MAC-OS or repository/conda installation)

If you still have this problem would you be able to re-install and compile the repository from scratch to see if it persists? Make sure to run 'python config.py compile' while using the 'ivs_repo_3.6' environment.

**Comment by karandis** [comment]
Seems to be fixed for now! 👍
